apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-4
  labels:
    app: myapp-4
spec:
  selector:
    matchLabels:
      app: myapp-4
  template:
    metadata:
      labels:
        app: myapp-4
    spec:
      containers:
        - name: container-1
          image: ubuntu:16.04
          command: ["/bin/bash"]
          args: ["-c", "sleep 100d"]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-5
  labels:
    app: myapp-5
spec:
  selector:
    matchLabels:
      app: myapp-5
  template:
    metadata:
      labels:
        app: myapp-5
    spec:
      containers:
        - name: container-1
          image: ubuntu:16.04
          command: ["/bin/bash"]
          args: ["-c", "sleep 100d"]
